language: php

php:
    - 7.1
    - 7.2
    - 7.3
    - 7.4

env:
    matrix:
        - PREFER_LOWEST="--prefer-lowest"
        - PREFER_LOWEST=""

services:
    - mysql

before_script:
    - travis_retry composer self-update
    - travis_retry composer update --prefer-source --ignore-platform-reqs --no-interaction $PREFER_LOWEST
    - travis_retry wget https://scrutinizer-ci.com/ocular.phar
    - mkdir -p build/logs
    - mysql -u root --password="" < test/Fixtures/dbscheme.sql

script:
    - vendor/bin/phpunit --coverage-clover=build/logs/clover.xml

after_script:
    - php ocular.phar code-coverage:upload --format=php-clover build/logs/clover.xml
